# -*- coding: utf-8 -*-
"""LoanApproval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjwSlyfY_lcTYYGNT_UTSjY9HaNTzb4w
"""

from google.colab import files
uploaded= files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('loan_data.csv.xls')

df.info()

df.head()

df.describe()

"""### Feature Scaling Numerical Data

To prepare the data for machine learning models, we will scale the numerical features. This helps to normalize the range of independent variables or features of the data. We will use `StandardScaler` which standardizes features by removing the mean and scaling to unit variance.
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Separate features (X) and target (y)
# Create a copy to avoid modifying the original DataFrame directly
df_processed = df.copy()
X = df_processed.drop('loan_status', axis=1)
y = df_processed['loan_status']

# Identify numerical and categorical columns
numerical_features = X.select_dtypes(include=np.number).columns
categorical_features = X.select_dtypes(include='object').columns

# Create a preprocessing pipeline for numerical features (MinMaxScaler) and categorical features (OneHotEncoder)
preprocessor = ColumnTransformer(
    transformers=[
        ('num', MinMaxScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough' # Keep any other columns (e.g., if there were non-numeric, non-categorical)
)

# Apply the preprocessing steps to X
X_processed = preprocessor.fit_transform(X)

# If you want to convert X_processed back to a DataFrame with column names (optional, but good for inspection)
# Get feature names after one-hot encoding
encoded_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features)
all_feature_names = list(numerical_features) + list(encoded_feature_names)

X_final = pd.DataFrame(X_processed, columns=all_feature_names, index=X.index)

# Split the processed data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)

print("X_train shape after scaling and encoding:", X_train.shape)
print("X_test shape after scaling and encoding:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nPreview of X_train (first 5 rows, first 10 columns):")
display(X_train.iloc[:5, :10])

"""#1. Via KNN MODEL-->"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size = 0.2, random_state = 42)

from sklearn.neighbors import KNeighborsClassifier

accuracy_list = []

from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer

# Clear the accuracy list before running the loop
accuracy_list = []

# Initialize imputer to fill NaNs, e.g., with the mean of the column
imputer = SimpleImputer(strategy='mean')

for i in range(1, 10):

  knn = KNeighborsClassifier(n_neighbors = i)

  # Impute NaNs in X_train and X_test before fitting
  # Fit the imputer on X_train and transform both training and test sets
  X_train_imputed = imputer.fit_transform(X_train)
  X_test_imputed = imputer.transform(X_test)

  knn.fit(X_train_imputed, y_train)

  # Finding the Predicted Values of the KNN Model

  y_prediction = knn.predict(X_test_imputed)

  # Finding the Accuracy

  acs = accuracy_score(y_test, y_prediction)

  # Adding the Accuracy Score to the List

  accuracy_list.append(acs)

plt.plot(range(1, len(accuracy_list) + 1), accuracy_list, marker = 'o')

plt.xlabel('Value of K')
plt.ylabel('Accuracy')
plt.title('Elbow Method for K-NN: Value of K vs. Accuracy')
plt.grid()

plt.show()

# Display the full accuracy list
print("Accuracy list for k=1 to 10:")
print(accuracy_list)

# Find the maximum accuracy and its corresponding k value
max_accuracy = max(accuracy_list)
best_k = accuracy_list.index(max_accuracy) + 1 # +1 because k starts from 1, not 0 index

print(f"\nThe maximum accuracy achieved is: {max_accuracy:.4f}")
print(f"The optimal 'k' value for this accuracy is: {best_k}")

"""#2. Via RandomForestClassifier"""

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

"""#3. Via SVM-->"""

