# -*- coding: utf-8 -*-
"""Clustering(KNN-means).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDjeR6lef_TQwj4yT9UYMqi8qOonNJ8s
"""

#from google.colab import files

#uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('student_clustering.csv')

df.info(

)

df.describe()

sns.scatterplot(data = df, x = 'cgpa', y = 'iq')

from sklearn.cluster import KMeans

model = KMeans(n_clusters = 2)

model.fit_predict(df[['cgpa', 'iq']])

model.inertia_

inr_list = []
for i in range(1,15):
  model = KMeans(n_clusters= i)
  model.fit(df)

  inr = model.inertia_

  inr_list.append(inr)

print(inr_list)

plt.plot(range(1,15), inr_list)

plt.xlabel("Value of K")
plt.ylabel("Inertia")
plt.title("K vs Interia")

plt.show()