# -*- coding: utf-8 -*-
"""KMeans example #2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJ6PwKoEy1XzTqyBougMDmakl0An1Tf2
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('circles_dataset.csv')

df.info()

df.head(
)

sns.scatterplot(data = df)

from sklearn.cluster import KMeans

inr_list = []
for i in range(1, 15):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10) # n_init is set to 10 to suppress future warning
    kmeans.fit(df)
    inr_list.append(kmeans.inertia_)

print(inr_list)

plt.plot(range(1,15), inr_list)

plt.xlabel("Value of K")
plt.ylabel("Inertia")
plt.title("K vs Interia")

plt.show()