# -*- coding: utf-8 -*-
"""CricNomics(Reg).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2eNCra6lJ-EGe4fYOIL5Zy09FtoqMnt
"""

from google.colab import files
uploaded= files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('IPL_data.csv')

df.info()

df.head()

df.describe()

y = df['SOLD PRICE']
# Re-including categorical features and essential numerical stats
# We drop identifiers like Sl.NO., PLAYER NAME, and TEAM
essential_df = df.drop(columns=['SOLD PRICE', 'Sl.NO.', 'PLAYER NAME', 'TEAM'])

# One-hot encoding for categorical variables
X = pd.get_dummies(essential_df, columns=['COUNTRY', 'PLAYING ROLE', 'AGE'], drop_first=True)

print(f"Total features after encoding: {X.shape[1]}")
X.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

model=RandomForestRegressor()

model.fit(X_train,y_train) #to make bestfit line

y_prediction =model.predict(X_test)

r2=r2_score(y_prediction,y_test)
print(r2)

from sklearn.linear_model import LinearRegression, Ridge
import xgboost as xgb

# Split using the restored feature set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(alpha=1.0),
    'Random Forest': RandomForestRegressor(n_estimators=100, max_depth=8, random_state=42),
    'XGBoost': xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    r2_val = r2_score(y_test, preds)
    # Using 100 - MAPE as an 'accuracy' proxy
    mape_val = np.mean(np.abs((y_test - preds) / y_test)) * 100
    results.append({
        'Model': name,
        'R2 Score': r2_val,
        'Accuracy (100-MAPE)': 100 - mape_val
    })

performance_df = pd.DataFrame(results).sort_values(by='R2 Score', ascending=False)
display(performance_df)

import numpy as np
from sklearn.model_selection import GridSearchCV

# 1. Log transform the target variable to stabilize variance and improve MAPE
y_log = np.log1p(y)
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(X, y_log, test_size=0.2, random_state=42)

# 2. Hyperparameter tuning for Random Forest to push accuracy higher
rf_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 15, 20],
    'min_samples_leaf': [1, 2]
}

grid_rf = GridSearchCV(RandomForestRegressor(random_state=42), rf_params, cv=3, scoring='r2')
grid_rf.fit(X_train_l, y_train_l)

# 3. Evaluate the best model
best_model = grid_rf.best_estimator_
log_preds = best_model.predict(X_test_l)

# Convert predictions back to original price scale
final_preds = np.expm1(log_preds)
actual_y = np.expm1(y_test_l)

# Calculate final metrics
final_r2 = r2_score(actual_y, final_preds)
final_mape = np.mean(np.abs((actual_y - final_preds) / actual_y)) * 100
final_accuracy = 100 - final_mape

print(f"Best RF Params: {grid_rf.best_params_}")
print(f"Improved R2 Score: {final_r2:.4f}")
print(f"Improved Accuracy (100-MAPE): {final_accuracy:.2f}%")